---

name: Build
on:
  push:
    # tags:
    #   - '*'

jobs:

  build-packages:
    name: Build and upload artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            bin: phasmo-tracker
          - os: windows-latest
            cc: msvc
            bin: phasmo-tracker.exe

    steps:

      - uses: actions/checkout@v3

      - if: runner.os == 'Linux'
        name: Install dependencies (linux)
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      # - if: runner.os == 'Windows'
      #   name: Install dependencies (windows)
      #   run: |
      #     sudo apt update
      #     sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - uses: finwo/dep@main
        name: Install dep

      - name: Install dependencies
        run: dep install
        shell: bash

      - if: runner.os == 'Linux'
        name: List everything
        run: find .

      - name: Build
        run: make CC=${{ matrix.cc }} BIN=${{ matrix.bin }}

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ${{ matrix.bin }}
      #     file_glob: true
      #     overwrite: true
      #     tag: ${{ github.ref }}
