---

name: Build
on:
  push:
    tags:
      - '*'

jobs:

  build-packages:
    name: Attach packages to release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cc: gcc
          - cc: x86_64-w64-mingw32-gcc

    steps:

      - uses: finwo/dep@edge
        name: Install dep

      - uses: actions/checkout@v3

      - name: test
        run: echo hello world
