---

name: Build
on:
  push:
    tags:
      - '*'

jobs:

  build-windows:
    name: Build and upload artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            cc: clang
            cpp: clang++
            bin: phasmo-tracker-win-x64.exe
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (windows)
        run: |
          mkdir external
          mkdir external\\tools
          mkdir external\\libs
          curl -sSLo "external\\tools\\nuget.exe" https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
          external\\tools\\nuget install Microsoft.Web.Webview2 -Verbosity quiet -Version "1.0.1150.38" -OutputDirectory "external\\libs" || exit /b 1

      - shell: bash
        run: |
          echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH

      - uses: finwo/dep@main
        name: Install dep

      - name: Install dependencies
        run: dep install
        shell: bash

      - name: Build
        run: make CC=${{ matrix.cc }} CPP=${{ matrix.cpp }} BIN=${{ matrix.bin }}
        shell: bash

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bin }}
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}

  build-linux:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - distro: ubuntu_latest
            arch: aarch64
            cc: gcc
            cpp: g++
            bin: phasmo-tracker-lin-aarch64

          - distro: ubuntu_latest
            arch: armv7
            cc: gcc
            cpp: g++
            bin: phasmo-tracker-lin-armv7

          - distro: ubuntu_latest
            arch: riscv64
            cc: gcc
            cpp: g++
            bin: phasmo-tracker-lin-riscv64

          - distro: ubuntu_latest
            arch: none
            cc: gcc
            cpp: g++
            bin: phasmo-tracker-lin-x64

    steps:

      - uses: actions/checkout@v3

      - uses: finwo/dep@main
        name: Install dep

      - name: Install dependencies
        run: dep install
        shell: bash

      - if: ${{ matrix.arch != 'none' }}
        uses: uraimo/run-on-arch-action@v2
        name: Build
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}

          install: |
            apt-get update -yq
            apt-get install -yq build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libglib2.0-dev nodejs

          run: |
            make CC=${{ matrix.cc }} CPP=${{ matrix.cpp }} BIN=${{ matrix.bin }}

      - if: ${{ matrix.arch == 'none' }}
        name: Build
        shell: bash
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq libgtk-3-dev libwebkit2gtk-4.0-dev libglib2.0-dev
          make CC=${{ matrix.cc }} CPP=${{ matrix.cpp }} BIN=${{ matrix.bin }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bin }}
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
