---

name: Build
on:
  push:
    tags:
      - '*'

jobs:

  build-packages:
    name: Attach packages to release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:

      - name: Install mingw and make
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          choco install mingw
          choco install make

      - uses: actions/checkout@v3

      - name: test
        run: echo hello world
