---

name: Build
on:
  push:
    tags:
      - '*'

jobs:

  build-packages:
    name: Attach packages to release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:

      - name: Install Chocolatey pkg
        uses: Tyler887/chocolatey-install@1.0
        if: ${{ startsWith(matrix.os, 'windows-') }}

      - name: Install mingw
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: choco install mingw

      - uses: actions/checkout@v3

      - name: test
        run: echo hello world
