---

name: Build
on:
  push:
    tags:
      - '*'

jobs:

  build-packages:
    name: Attach packages to release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:

      - uses: finwo/dep@edge
        name: Install dep
        shell: bash

      - uses: actions/checkout@v3

      - name: test
        run: echo hello world
